In [ ]:
def convert_units(conversion_type, value):
    if conversion_type == 1:  #meters to feet
        return value * 3.28084
    elif conversion_type == 2:  #feet to meters
        return value / 3.28084
    elif conversion_type == 3:  #kilograms to pounds
        return value * 2.20462
    elif conversion_type == 4:  #pounds to kilograms
        return value / 2.20462
    elif conversion_type == 5:  #liters to gallons
        return value * 0.264172
    elif conversion_type == 6:  #gallons to liters
        return value / 0.264172
    else:
        return None


def main():
    print("Unit Conversion Program")
    print("Choose a conversion type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Enter your choice (1-6): "))
        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is None:
            print("Error: Unsupported conversion type.")
        else:
            print(f"Converted value: {result:.2f}")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    main()

In [ ]:
def calculate_sum(numbers):
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))

        user_input = input("Enter numbers: ")
        numbers = list(map(float, user_input.split()))

        if len(numbers) == 0:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            result = calculate_sum(numbers)
            print("Sum:", result)
        elif choice == 2:
            result = calculate_average(numbers)
            print("Average:", result)
        elif choice == 3:
            result = find_maximum(numbers)
            print("Maximum:", result)
        elif choice == 4:
            result = find_minimum(numbers)
            print("Minimum:", result)
        else:
            print("Error: Invalid operation selected.")

    except ValueError:
        print("Error: Please enter valid numbers.")


if __name__ == "__main__":
    main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 2 3 4 5 
Sum: 14.0


In [ ]:
def extract_every_other(lst):
    return lst[::2]

numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)

[3, 4, 5]


In [ ]:
def reverse_list(lst):
    return lst[::-1]

numbers = [1, 2, 3, 4, 5]
reversed_numbers = reverse_list(numbers)
print(reversed_numbers)

[5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


In [ ]:
def get_first_n(lst, n):
    return lst[:n]

numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print(result)

[1, 2, 3]


In [ ]:
def get_last_n(lst, n):
    return lst[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


In [ ]:
def get_last_n(lst, n):
    return lst[-n:]
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)

[5, 3, 1]


In [ ]:
def flatten(lst):
    flattened_list = []
    for sublist in lst:
        flattened_list.extend(sublist)
    return flattened_list

nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print(result)

[1, 2, 3, 4, 5]


In [1]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)

6


In [2]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr1 = np.empty((2, 2))

# 2. Initialize an all one array with size 4x2
arr2 = np.ones((4, 2))

# 3. Return a new array of given shape filled with a specific value
arr3 = np.full((3, 3), 7)

# 4. Return a new array of zeros with same shape and type as arr2
arr4 = np.zeros_like(arr2)

# 5. Return a new array of ones with same shape and type as arr2
arr5 = np.ones_like(arr2)

# 6. Convert list to NumPy array
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)

# Print all results
print("Empty array (2x2):\n", arr1)
print("\nOnes array (4x2):\n", arr2)
print("\nFull array (3x3) filled with 7:\n", arr3)
print("\nZeros like arr2:\n", arr4)
print("\nOnes like arr2:\n", arr5)
print("\nList converted to NumPy array:\n", arr6)

Empty array (2x2):
 [[5.33701296e-316 0.00000000e+000]
 [7.50573672e+247 6.81110136e+199]]

Ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array (3x3) filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like arr2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones like arr2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

List converted to NumPy array:
 [1 2 3 4]


In [4]:
import numpy as np

# 1. Array with values from 10 to 49
arr1 = np.arange(10, 50)

# 2. 3x3 matrix with values from 0 to 8
arr2 = np.arange(9).reshape(3, 3)

# 3. 3x3 identity matrix
arr3 = np.eye(3)

# 4. Random array of size 30 and its mean
arr4 = np.random.random(30)
mean_val = arr4.mean()

# 5. 10x10 random array and find min & max
arr5 = np.random.random((10, 10))
min_val = arr5.min()
max_val = arr5.max()

# 6. Zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1   # index 4 = 5th element

# 7. Reverse array
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr7[::-1]

# 8. 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0

# 9. 8x8 checkerboard pattern
arr9 = np.zeros((8, 8))
arr9[::2, ::2] = 1
arr9[1::2, 1::2] = 1

# Print results
print("1. Range 10–49:\n", arr1)
print("\n2. 3x3 matrix 0–8:\n", arr2)
print("\n3. Identity matrix:\n", arr3)
print("\n4. Random array mean:\n", mean_val)
print("\n5. Min:", min_val, "Max:", max_val)
print("\n6. Zero array with 5th element = 1:\n", arr6)
print("\n7. Reversed array:\n", reversed_arr)
print("\n8. Border 1s, inside 0s:\n", arr8)
print("\n9. Checkerboard pattern:\n", arr9)

1. Range 10–49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix 0–8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array mean:
 0.5174836218718873

5. Min: 0.01024619196365295 Max: 0.9994511374359607

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. Border 1s, inside 0s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [5]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add arrays
add_xy = x + y

# 2. Subtract arrays
sub_xy = x - y

# 3. Multiply array with integer
mul_x = x * 2

# 4. Square each element
square_x = x ** 2

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

# 6. Concatenation
concat_xy_row = np.concatenate((x, y), axis=0)   # row-wise
concat_vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)

# Print results
print("Add:\n", add_xy)
print("\nSubtract:\n", sub_xy)
print("\nMultiply x by 2:\n", mul_x)
print("\nSquare of x:\n", square_x)

print("\nDot product v·w:", dot_vw)
print("Dot product x·v:\n", dot_xv)
print("Dot product x·y:\n", dot_xy)

print("\nConcatenate x & y (rows):\n", concat_xy_row)
print("\nConcatenate v & w (columns):\n", concat_vw_col)

Add:
 [[ 6  8]
 [10 13]]

Subtract:
 [[-4 -4]
 [-4 -3]]

Multiply x by 2:
 [[ 2  4]
 [ 6 10]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]

Concatenate x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v & w (columns):
 [[ 9 11]
 [10 12]]
